name: "app-j25"

services:
  app-db-service:
    image: mysql:${DB_VERSION:-latest}
    container_name: app-db-container
    networks:
      internal-net-app:
        ipv4_address: 192.168.10.3
        ipv6_address: 2001:3984:3989::13
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=job-vacancies-app-db
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    restart: on-failure
    volumes:
      - mysql-data:/var/lib/mysql
      - //c/Programacion/git/JobVacanciesApp_Java25/src/main/resources/db_dumps:/docker-entrypoint-initdb.d
#      - mysql-logs:/var/log/mysql
    cap_add:
      - SYS_NICE
    env_file:
      - .env
    healthcheck:
      test: "mysql -uroot -p${DB_ROOT_PASSWORD:-root} -e 'select 1'"
      interval: 1s
      retries: 120

  app-service:
    image: job-vacancies-app:${APP_VERSION:-1.0}
    container_name: app-container
    networks:
      internal-net-app:
        ipv4_address: 192.168.10.2
        ipv6_address: 2001:3984:3989::12
      external-net-app:
#        ipv4_address: 192.168.20.2
#        ipv6_address: 2001:3984:3990::22
    ports:
      - ${APP_PORT:-8080}:8080
    environment:
      - MYSQL_HOST=app-db-container
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - EXTERNAL_FILES_PATH=/AppData_Java25/JobVacanciesApp
    restart: on-failure
    volumes:
      - //c/AppData_Java25/JobVacanciesApp:/AppData_Java25/JobVacanciesApp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: lib/*.jar
        PRINT_ARG: new_value
    env_file:
      - .env
    depends_on:
      app-db-service:
        condition: service_healthy

networks:
  internal-net-app:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::11
  external-net-app:
    external: true
    driver: bridge
    enable_ipv6: true
#  external-net-app:
#    driver: bridge
#    enable_ipv6: true
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.20.0/24
#          gateway: 192.168.20.1
#        - subnet: 2001:3984:3990::/64
#          gateway: 2001:3984:3990::21

volumes:
  mysql-data:
    driver: local
#  mysql-logs:
#    driver: local
